CREATE TABLE BANKS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE BANKS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BANKS_BEFORE_INSERT
BEFORE INSERT ON BANKS
FOR EACH ROW
BEGIN
    SELECT BANKS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE REVIEWS (
    ID NUMBER PRIMARY KEY,
    BANK_ID NUMBER NOT NULL,
    REVIEW_TEXT CLOB NOT NULL,
    RATING NUMBER(2,1),
    REVIEW_DATE DATE,
    SOURCE VARCHAR2(100),
    CLEANED_TEXT CLOB,
    SENTIMENT_LABEL VARCHAR2(20),
    SENTIMENT_SCORE FLOAT,
    KEYWORDS CLOB,
    THEMES CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BANK FOREIGN KEY (BANK_ID) REFERENCES BANKS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE REVIEWS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER REVIEWS_BEFORE_INSERT
BEFORE INSERT ON REVIEWS
FOR EACH ROW
BEGIN
    SELECT REVIEWS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
